---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  dependsOn:
  - name: kube-prometheus-stack
    namespace: monitoring
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/miguelndecarvalho/speedtest-exporter
              tag: v3.5.4
            env:
              SPEEDTEST_SERVER: "39677"
            resources:
              requests:
                cpu: 15m
                memory: 50M
              limits:
                memory: 100M
    service:
      main:
        ports:
          http:
            port: 9798
    serviceMonitor:
      main:
        enabled: true
        serviceName: main
        endpoints:
        - port: http
          scheme: http
          path: /metrics
          interval: 30m
          scrapeTimeout: 3m
