---
- hosts: chief
  remote_user: "{{ default_user }}"
  become: true
  gather_facts: false

  roles:
  - install-k3s-chief
  - upgrade-host

- hosts: master
  remote_user: "{{ default_user }}"
  become: true
  gather_facts: false

  roles:
  - install-k3s-master
  - upgrade-host

- hosts: worker
  remote_user: "{{ default_user }}"
  become: true
  serial: true
  gather_facts: true

  roles:
  - install-k3s-worker
  - upgrade-host
