---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-pv-gtd
spec:
  storageClassName: nas-pv-gtd
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_SERVER_PATH_PV}/gtd
  mountOptions:
  - nfsvers=4
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
  - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-pv-gtd
  namespace: gtd
spec:
  storageClassName: nas-pv-gtd
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
