---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.9.9
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  values:
    toolbox:
      enabled: false
    monitoring:
      enabled: true
      createPrometheusRules: false
    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard = true
    cephClusterSpec:
      network:
        provider: host
      resources:
        mgr:
          requests:
            cpu: "125m"
            memory: "549M"
          limits:
            memory: "1219M"
        mon:
          requests:
            cpu: "49m"
            memory: "477M"
          limits:
            memory: "1059M"
        osd:
          requests:
            cpu: "442m"
            memory: "2678M"
          limits:
            memory: "5944M"
        prepareosd:
          requests:
            cpu: "250m"
            memory: "50Mi"
          limits:
            memory: "200Mi"
        mgr-sidecar:
          requests:
            cpu: "49m"
            memory: "94M"
          limits:
            memory: "208M"
        crashcollector:
          requests:
            cpu: "15m"
            memory: "64M"
          limits:
            memory: "64M"
        logcollector:
          requests:
            cpu: "100m"
            memory: "100M"
          limits:
            memory: "1G"
        cleanup:
          requests:
            cpu: "250m"
            memory: "100M"
          limits:
            memory: "1G"
      crashCollector:
        disable: false
      dashboard:
        enabled: true
        urlPrefix: /
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
        - name: "higgs-master-1"
          devices:
          - name: "/dev/sdb"
        - name: "higgs-worker-1"
          devices:
          - name: "/dev/sdb"
        - name: "higgs-worker-2"
          devices:
          - name: "/dev/sdb"
        - name: "higgs-worker-3"
          devices:
          - name: "/dev/sdb"
    ingress:
      ingressClassName: "nginx"
      dashboard:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        host:
          name: rook.buvis.net
          path: "/"
        tls:
        - hosts:
          - rook.buvis.net
    cephBlockPoolsVolumeSnapshotClass:
      enabled: false
    cephBlockPools:
    - name: ceph-blockpool
      spec:
        failureDomain: host
        replicated:
          size: 3
      storageClass:
        enabled: true
        name: ceph-block
        isDefault: true
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        parameters:
          imageFormat: "2"
          imageFeatures: layering
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
          csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
          csi.storage.k8s.io/fstype: ext4
