---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-buckets
  namespace: storage
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
