---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 10m
  url: https://openebs-archive.github.io/jiva-operator
  timeout: 3m
