---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  dependsOn:
  - name: thanos
    namespace: monitoring
  - name: prometheus
    namespace: monitoring
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    loki:
      config:
        storage_config:
          aws:
            bucketnames: loki
            endpoint: "minio.monitoring.svc.cluster.local"
            access_key_id: "${SECRET_MINIO_THANOS_ACCESSKEY}"
            secret_access_key: "${SECRET_MINIO_THANOS_SECRETKEY}"
            s3forcepathstyle: true
            insecure: true
          boltdb_shipper:
            active_index_directory: /data/loki/index
            cache_location: /data/loki/index_cache
            resync_interval: 5s
            shared_store: s3
