---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blocky
  namespace: network
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: blocky
      app.kubernetes.io/name: blocky
      app.kubernetes.io/service: blocky
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
    scrapeTimeout: 10s
