---
ignore: |
  .github/
  cluster-secrets.yaml
  gotk-components.yaml
  vault.yaml
  production-old/operations/vpn/vpn-gateway/secret.yaml
  production-old/operations/kube-system/cert-manager/secrets.yaml
  production-old/infrastructure/manifests/deploy-tigera-operator.yaml
  production/operations/kube-system/cert-manager/secrets.yaml
  production/operations/minio-operator/minio/secret.yaml
  production/operations/monitoring/thanos/secret.yaml
extends: default
rules:
  truthy:
    allowed-values: ['true', 'false', 'on', 'yes']
  comments:
    min-spaces-from-content: 1
  line-length: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: false
