---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media-music-radio
spec:
  storageClassName: nas-media-music-radio
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${FAST_NAS_SERVER_IP}
    path: ${FAST_NAS_PATH_MEDIA}/music
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media-music-radio
  namespace: radio
spec:
  storageClassName: nas-media-music-radio
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
