---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: openebs
    namespace: storage
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
        - 44
        - 109
        - 65539
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/jellyfin
              tag: 10.8.11@sha256:926e2a9f6677a0c7b12feba29f36c954154869318d6a52df72f72ff9c74cf494
        env:
          JELLYFIN_CACHE_DIR: /config/cache
          DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
        resources:
          requests:
            cpu: 100m
            memory: 4282M
          limits:
            memory: 12G
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-data
      media:
        enabled: true
        existingClaim: nas-media-videos
        globalMounts:
        - path: /media/videos
      transcode:
        enabled: true
        type: emptyDir
    service:
      main:
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_JELLYFIN}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8096
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
        - host: jellyfin.buvis.net
          paths:
          - path: /
            service:
              name: main
              port: http
        tls:
        - hosts:
          - jellyfin.buvis.net
          secretName: jellyfin-crt
