---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: openebs
    namespace: storage
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.8@sha256:f43a14b5936c90972ec379b6ff64e377163d2b41c03a08f6b0e32242939546a3
    env:
      TZ: ${TIMEZONE}
      JELLYFIN_CACHE_DIR: /config/cache
      DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-data
      media:
        enabled: true
        existingClaim: nas-media
        mountPath: /media
      transcode:
        enabled: true
        type: emptyDir
    service:
      main:
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_JELLYFIN}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8096
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
        - host: jellyfin.buvis.net
          paths:
          - path: /
        tls:
        - hosts:
          - jellyfin.buvis.net
          secretName: jellyfin-crt
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 65539
    resources:
      requests:
        cpu: 100m
        memory: 4282M
      limits:
        memory: 12G
