---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
  namespace: media
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
