---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kopia-ui
  namespace: storage
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: authentik
    namespace: security
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    initContainers:
      wait-for-repo:
        image: ghcr.io/onedr0p/kopia:0.13.0@sha256:ee6608635237c9ddf3ec5b456122cb60f0195c5cad84b06e945498f2338bff59
        command:
        - /bin/bash
        - -c
        - |-
          until [ -f /snapshots/kopia.repository.f ]; do
              printf "\e[1;32m%-6s\e[m\n" "Waiting for the Kopia repo to become ready ..."
              sleep 1
          done
        volumeMounts:
        - name: snapshots
          mountPath: /snapshots
    image:
      repository: ghcr.io/onedr0p/kopia
      tag: 0.13.0@sha256:ee6608635237c9ddf3ec5b456122cb60f0195c5cad84b06e945498f2338bff59
    env:
      KOPIA_PASSWORD: "none"
    command: kopia
    args:
    - server
    - start
    - --insecure
    - --address
    - 0.0.0.0:80
    - --metrics-listen-addr
    - 0.0.0.0:8080
    - --without-password
    - --log-level
    - debug
    service:
      main:
        enabled: true
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_KOPIA}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 80
          metrics:
            enabled: true
            port: 8080
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          authentik.home.arpa/enabled: "true"
        hosts:
        - host: kopia.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - kopia.buvis.net
          secretName: kopia-crt
    podSecurityContext:
      supplementalGroups:
      - 100
    persistence:
      config:
        enabled: true
        type: configMap
        name: kopia-ui-config
        subPath: repository.config
        mountPath: /config/repository.config
        readOnly: true
      snapshots:
        enabled: true
        type: nfs
        server: ${NFS_SERVER_IP}
        path: ${NFS_SERVER_PATH_KOPIA}/snapshots
        mountPath: /snapshots
