---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-demo-db
  namespace: development
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
