---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-wireguard
spec:
  storageClassName: nas-wireguard
  capacity:
    storage: 10Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_SERVER_PATH_WIREGUARD}
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: wireguard-config
    namespace: network
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config
  namespace: network
spec:
  storageClassName: nas-wireguard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
