---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: wireguard
  name: wireguard
  namespace: network
spec:
  type: LoadBalancer
  externalIPs:
  - ${SVC_IP_WIREGUARD}
  externalTrafficPolicy: Local
  ports:
  - port: 51820
    targetPort: 51820
    protocol: UDP
  selector:
    app: wireguard
