---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zettelkasten
  namespace: gtd
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-system
  - name: cert-manager
    namespace: kube-system
  - name: oauth2-proxy
    namespace: kube-system
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.buvis.net
      chart: mkdocs-git-sync
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: buvis
        namespace: flux-system
      interval: 5m
  values:
    config:
      repo: https://gitlab.com/buvis/zettelkasten.git
      credentials: ${SECRET_ZETTELKASTEN_REPO_CREDENTIALS}
      branch: main
      docsDir: zettelkasten
      editUri: https://gitlab.com/buvis/zettelkasten/edit/main/zettelkasten
      updateInterval: 60
      siteName: Bob's Zettelkasten
      siteUrl: https://zettelkasten.buvis.net
      requirements: |
        mkdocs-zettelkasten==0.1.5
        git+https://github.com/jldiaz/mkdocs-plugin-tags.git#egg=tags-macros-plugin
      theme:
        name: zettelkasten-solarized-light
      extensions:
      - admonition
      - pymdownx.superfences
      plugins:
      - search
      - tags
      - zettelkasten
      nav:
      - Source: https://gitlab.com/buvis/zettelkasten
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: zerossl
        nginx.ingress.kubernetes.io/auth-url: "https://auth.buvis.net/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.buvis.net/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
      hosts:
      - host: zettelkasten.buvis.net
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: zettelkasten-crt
        hosts:
        - zettelkasten.buvis.net
