apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-higgs-worker-1
  namespace: storage
spec:
  restartPolicy: Never
  nodeName: higgs-worker-1
  containers:
    - name: disk-wipe
      image: ubuntu
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      args:
        [
          "apt update; apt install fdisk gdisk parted udev -y; sgdisk --zap-all /dev/sdb; dd if=/dev/zero bs=1M count=100 oflag=direct,dsync of=/dev/sdb; wipefs -af /dev/sdb; blkdiscard /dev/sdb; partprobe /dev/sdb",
        ]
