---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
  namespace: media
  labels:
    app.kubernetes.io/name: jellyseerr
    app.kubernetes.io/instance: jellyseerr
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
