---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-operators
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager
  interval: 10m0s
  path: ./cluster-home/operations/kube-tools/cert-manager/operators
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: Secret
      name: cluster-secret-vars
    - kind: ConfigMap
      name: cluster-config
