---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-prometheus-rules
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager
  - name: kube-prometheus-stack
  interval: 10m0s
  path: ./cluster-home/operations/kube-tools/cert-manager/prometheus-rules
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: Secret
      name: cluster-secret-vars
    - kind: ConfigMap
      name: cluster-config
