---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-operators
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./production/operations/kube-system/cert-manager/operators
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: Secret
      name: cluster-secret-vars
    - kind: Secret
      name: zerossl-eab
    - kind: Secret
      name: route53-credentials
    - kind: ConfigMap
      name: cluster-config
