---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr
  namespace: media
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: authentik
    namespace: security
  - name: openebs
    namespace: storage
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      tdarr:
        containers:
          app:
            image:
              repository: haveagitgat/tdarr
              tag: 2.24.05@sha256:9fb794f39259b56c85ac8c439b7b8d5150f9c86dc30726f9811c59a88f38ca05
          node:
            image:
              repository: haveagitgat/tdarr_node
              tag: 2.24.05@sha256:a0efc8c0e995ae3d767e1bc3fcab4110b44e94e2b452b04e77d4c24e53965eed
            env:
            - name: nodeID
              value: node
            - name: serverIP
              value: localhost
            - name: serverPort
              value: 8266
    persistence:
      config:
        enabled: true
        existingClaim: tdarr-config
        globalMounts:
        - path: /app/configs
      data:
        enabled: true
        existingClaim: tdarr-data
        globalMounts:
        - path: /app/server
      media:
        enabled: true
        existingClaim: nas-media-videos
        globalMounts:
        - path: /media/videos
      shared:
        enabled: true
        existingClaim: nas-pv-media
        globalMounts:
        - subPath: tdarr/cache
    service:
      app:
        controller: tdarr
        ports:
          http:
            port: 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          authentik.home.arpa/enabled: "true"
        hosts:
        - host: &hostName tdarr.buvis.net
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
        tls:
        - hosts:
          - *hostName
          secretName: tdarr-crt
