---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr
  namespace: media
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: authentik
    namespace: security
  - name: openebs
    namespace: storage
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      tdarr:
        containers:
          app:
            image:
              repository: haveagitgat/tdarr
              tag: 2.23.01@sha256:3e08ace2525b7f0bc7f99246168ad01ba9f1ef58a6ddfdd7d229691d127f93fd
          node:
            image:
              repository: haveagitgat/tdarr_node
              tag: 2.23.01@sha256:c4c2ccfcb429d5db56db3a47ff16f27bdbdb1c7c9b623a57e6f0c1874d8f7fa2
            env:
            - name: nodeID
              value: node
            - name: serverIP
              value: localhost
            - name: serverPort
              value: 8266
    persistence:
      config:
        enabled: true
        existingClaim: tdarr-config
        globalMounts:
        - path: /app/configs
      data:
        enabled: true
        existingClaim: tdarr-data
        globalMounts:
        - path: /app/server
      media:
        enabled: true
        existingClaim: nas-media-videos
        globalMounts:
        - path: /media/videos
      shared:
        enabled: true
        existingClaim: nas-pv-media
        globalMounts:
        - subPath: tdarr/cache
    service:
      app:
        controller: tdarr
        ports:
          http:
            port: 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          authentik.home.arpa/enabled: "true"
        hosts:
        - host: &hostName tdarr.buvis.net
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
        tls:
        - hosts:
          - *hostName
          secretName: tdarr-crt
