---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr
  namespace: media
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: authentik
    namespace: security
  - name: openebs
    namespace: storage
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: haveagitgat/tdarr
      tag: 2.14.01@sha256:eafd921d9c4b550530b4f51e1de9e85b1dd567e31fcbb06382b99958db3de3ed
      pullPolicy: IfNotPresent
    additionalContainers:
      node:
        name: node
        image: haveagitgat/tdarr_node:2.13.01@sha256:f688c979884bc04ade022b75dc65378f1dd2d91dcc620cfdfb17e18b9c8df663
        imagePullPolicy: IfNotPresent
        env:
        - name: nodeID
          value: node
        - name: serverIP
          value: localhost
        - name: serverPort
          value: 8266
        volumeMounts:
        - name: config
          mountPath: /app/configs
        - name: media
          mountPath: /media
        - name: shared
          mountPath: /shared
    persistence:
      config:
        enabled: true
        existingClaim: tdarr-config
        mountPath: /app/configs
      data:
        enabled: true
        existingClaim: tdarr-data
        mountPath: /app/server
      media:
        enabled: true
        existingClaim: nas-media
        mountPath: /media
      shared:
        enabled: true
        type: pvc
        existingClaim: tdarr-cache
        mountPath: /shared
    service:
      main:
        ports:
          http:
            port: 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          authentik.home.arpa/enabled: "true"
        hosts:
        - host: tdarr.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - tdarr.buvis.net
          secretName: tdarr-crt
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
