---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  namespace: media
  labels:
    app.kubernetes.io/name: tdarr
    app.kubernetes.io/instance: tdarr
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-data
  namespace: media
  labels:
    app.kubernetes.io/name: tdarr
    app.kubernetes.io/instance: tdarr
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-tdarr-cache
spec:
  storageClassName: nas-tdarr-cache
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_SERVER_PATH_TDARR_CACHE}
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
  - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache
  namespace: media
spec:
  storageClassName: nas-tdarr-cache
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
