---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkace
  namespace: gtd
  labels:
    app.kubernetes.io/name: linkace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: linkace
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linkace
    spec:
      containers:
      - image: linkace/linkace:v1.10.0-simple
        name: linkace
        ports:
        - containerPort: 80
        env:
        # https://www.linkace.org/docs/v1/setup/setup-with-docker/advanced-configuration/#using-docker-environment-variables-instead-of-the-env-file
        - name: APP_KEY
          value: ${SECRET_LINKACE_APP_KEY}
        - name: DB_HOST
          value: linkace-db-mariadb.gtd
        - name: DB_DATABASE
          value: linkace
        - name: DB_USERNAME
          value: linkace
        - name: DB_PASSWORD
          value: ${SECRET_LINKACE_DB_PASSWORD}
        - name: SETUP_COMPLETED
          value: true
      restartPolicy: Always
