---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkace-db
  namespace: gtd
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://groundhog2k.github.io/helm-charts/
      chart: mariadb
      version: 0.4.1
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
        namespace: flux-system
      interval: 5m
  # See https://artifacthub.io/packages/helm/groundhog2k/mariadb
  values:
    storage:
      persistentVolumeClaimName: linkace-db
    userDatabase:
      name: linkace
      user: linkace
      password: ${SECRET_LINKACE_DB_PASSWORD}
    settings:
      rootPassword: ${SECRET_LINKACE_DB_ROOTPASSWORD}
