---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kopia
  namespace: flux-system
resources:
- configmap.yaml
- helmrelease.yaml
- jobs
spec:
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
