---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-outpost
  namespace: security
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - auth.buvis.net
    secretName: authentik-https-cert
  rules:
  - host: auth.buvis.net
    http:
      paths:
      - pathType: Prefix
        path: /outpost.goauthentik.io
        backend:
          service:
            name: authentik
            port:
              number: 80
