---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-outpost
  namespace: security
spec:
  rules:
  - host: auth.buvis.net
    http:
      paths: /outpost.goauthentik.io
      pathType: Prefix
      backend:
        service:
          name: authentik
          port:
            number: 80
