---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-db
  namespace: security
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: authentik
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
