---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-outpost
  namespace: security
spec:
  rules:
  - host: sonarr.buvis.net
    http:
      paths:
      - pathType: Prefix
        path: /outpost.goauthentik.io
        backend:
          service:
            name: authentik
            port:
              number: 80
