---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-outpost
  namespace: security
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  #tls:
  #- hosts:
    #- sonarr.buvis.net
    #secretName: sonarr-crt
  rules:
  - host: sonarr.buvis.net
    http:
      paths:
      - pathType: Prefix
        path: /outpost.goauthentik.io
        backend:
          service:
            name: authentik
            port:
              number: 80
