---
apiVersion: v1
kind: Secret
metadata:
  name: minio-thanos
  namespace: minio
type: Opaque
data:
  CONSOLE_ACCESS_KEY: ${SECRET_MINIO_THANOS_ACCESSKEY}
  CONSOLE_SECRET_KEY: ${SECRET_MINIO_THANOS_SECRETKEY}
