---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monica-config
  namespace: gtd
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: monica
    app.kubernetes.io/instance: monica
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
