---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vifm
  namespace: media
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 985
    controllers:
      vifm:
        containers:
          app:
            image:
              repository: ghcr.io/buvis/vifm
              tag: v0.13@sha256:cba270b72116a43f35aec02ecbb2aad7892ce1c02c5b182dbc1864e3b4299429
            stdin: true
            tty: true
    persistence:
      media:
        enabled: true
        existingClaim: nas-media-music
        globalMounts:
          - path: /media/music
