---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: oauth2-proxy
    namespace: kube-tools
  - name: kube-prometheus-stack
    namespace: monitoring
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: thanos
      version: 12.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  timeout: 20m
  values:
    query:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
      replicaLabel:
      - __replica__
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        pathType: Prefix
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-url: "https://auth.buvis.net/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.buvis.net/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
        hostname: thanos-query.buvis.net
        tls: true
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: false
    compactor:
      enabled: false
    storegateway:
      enabled: false
    ruler:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
