---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-exec
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-mopidy-library-rescan
  namespace: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-mopidy-library-rescan-pod-list-exec
  namespace: media
subjects:
- kind: ServiceAccount
  name: job-mopidy-library-rescan
  namespace: media
roleRef:
  kind: ClusterRole
  name: pods-list-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mopidy-rescan
  namespace: media
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mopidy-rescan
            image: buvis/kube-exec:v24.2.0
            imagePullPolicy: Always
            env:
            - name: NAMESPACE
              value: media
            - name: LABEL
              value: "app.kubernetes.io/name=mopidy"
            - name: COMMAND
              value: "/shim/scan-local.sh"
          serviceAccountName: job-mopidy-library-rescan
          restartPolicy: OnFailure
