---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-tools
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    config:
      clientID: ${SECRET_OAUTH2_PROXY_CLIENTID}
      clientSecret: ${SECRET_OAUTH2_PROXY_CLIENTSECRET}
      cookieSecret: ${SECRET_OAUTH2_PROXY_COOKIESECRET}
    extraArgs:
      whitelist-domain: .buvis.net
      cookie-domain: .buvis.net
      provider: github
    extraEnv:
    - name: OAUTH2_PROXY_SCOPE
      value: "user:email"
    authenticatedEmailsFile:
      enabled: true
      restricted_access: tomas@buvis.net
    ingress:
      enabled: true
      path: /
      hosts:
      - auth.buvis.net
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls:
      - secretName: oauth2-proxy-https-cert
        hosts:
        - auth.buvis.net
