---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-system-extras
  interval: 5m
  path: ./cluster-home/operations/kube-tools/oauth2-proxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: Secret
      name: cluster-secret-vars
    - kind: ConfigMap
      name: cluster-config
