---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: recyclarr
  namespace: media
resources:
- helmrelease.yaml
configMapGenerator:
- name: recyclarr-config
  namespace: media
  files:
  - config/recyclarr.yaml
