---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.9.0
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  dependsOn:
  - name: rook-ceph
  values:
    monitoring:
      enabled: true
    ingress:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: zerossl
        host:
          name: rook.buvis.net
          path: /
        tls:
        - hosts:
          - rook.buvis.net
    cephClusterSpec:
      dashboard:
        enabled: true
        urlPrefix: /
      storage:
        useAllNodes: true
        useAllDevices: true
        config:
          osdsPerDevice: "1"
    cephObjectStores: []
