---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: authentik
    namespace: security
  - name: vpn-gateway
    namespace: vpn
  - name: openebs
    namespace: storage
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.4@sha256:f0a74313d750bc437ba2ad34f3412de5ab9a978f3f5b74227a1bda69271fef3e
    env:
      UMASK: "022"
      QBITTORRENT__PORT: 8080
      QBITTORRENT__USE_PROFILE: "true"
    podAnnotations:
      setVPNGateway: "true"
    hostname: torr
    settings:
      automaticPortSetup: false
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      media:
        enabled: true
        existingClaim: nas-media
        mountPath: /media
    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: true
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_BITTORRENT}
        externalTrafficPolicy: Local
        ports:
          bittorrent:
            enabled: true
            port: ${SECRET_VPN_BT_FORWARD_PORT}
            protocol: TCP
            targetPort: ${SECRET_VPN_BT_FORWARD_PORT}
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          authentik.home.arpa/enabled: "true"
        hosts:
        - host: qb.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - qb.buvis.net
          secretName: qbittorrent-crt
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 985
    resources:
      requests:
        cpu: 49m
        memory: 765Mi
      limits:
        memory: 1426Mi
