---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: authentik
    namespace: security
  - name: vpn-gateway
    namespace: vpn
  - name: openebs
    namespace: storage
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      annotations:
        setVPNGateway: "true"
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
        - 985
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.4@sha256:b9af0f2173572a69d2c02eab8f701ef7b04f61689efe1c5338b96445d528dec4
            env:
              UMASK: "022"
              QBITTORRENT__PORT: 8080
              QBITTORRENT__USE_PROFILE: "true"
            resources:
              requests:
                cpu: 49m
                memory: 765Mi
              limits:
                memory: 1426Mi
    hostname: torr
    settings:
      automaticPortSetup: false
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      downloads:
        enabled: true
        existingClaim: nas-media-downloads
    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: 8080
      bittorrent:
        controller: qbittorrent
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_BITTORRENT}
        externalTrafficPolicy: Local
        ports:
          bittorrent:
            enabled: true
            port: ${SECRET_VPN_BT_FORWARD_PORT}
            protocol: TCP
            targetPort: ${SECRET_VPN_BT_FORWARD_PORT}
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          authentik.home.arpa/enabled: "true"
        hosts:
        - host: &hostName qb.buvis.net
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
        tls:
        - hosts:
          - *hostName
          secretName: qbittorrent-crt
