---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
