---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittools-tagging
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: qbittorrent
      namespace: media
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
    controllers:
      qbittools:
        type: cronjob
        cronjob:
          schedule: "@hourly"
        containers:
          app:
            image:
              repository: ghcr.io/buroa/qbtools
              tag: master@sha256:f292c42ee5ce3b83f5bd0465bfab82eea4fd65ced72ad52b025ba6ad9d95b372
            args:
              - tagging
              - --not-working
              - --unregistered
              - --added-on
              - --last-activity
              - --tracker-down
              - -s
              - qbittorrent-app.media.svc.cluster.local
              - -p
              - "8080"
              - -U
              - ${SECRET_QB_USERNAME}
              - -P
              - ${SECRET_QB_PASSWORD}
            resources:
              requests:
                memory: 250Mi
                cpu: 25m
              limits:
                memory: 500Mi
