---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittools-tagging
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: qbittorrent
      namespace: media
  values:
    controller:
      type: cronjob
      cronjob:
        schedule: "@hourly"
    image:
      repository: ghcr.io/buroa/qbtools
      tag: latest@sha256:dc8957554902738837d1d0a6b4c4af5e27e1454341b0d9df5992be51cc1ecd65
    args:
      - tagging
      - --not-working
      - --unregistered
      - --added-on
      - --last-activity
      - --tracker-down
      - -s
      - qbittorrent-app.media.svc.cluster.local
      - -p
      - "8080"
      - -U
      - ${SECRET_QB_USERNAME}
      - -P
      - ${SECRET_QB_PASSWORD}
    service:
      main:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 500Mi
