---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mopidy
  namespace: radio
spec:
  dependsOn:
  - name: openebs
    namespace: storage
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.buvis.net
      chart: mopidy
      version: 0.5.1
      sourceRef:
        kind: HelmRepository
        name: buvis
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/buvis/mopidy
      tag: v3.65.0@sha256:9655c393f7c57658b3b76255d219a3dc779974bc68eb8ee41374c43cf6e5416f
    service:
      main:
        enabled: true
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_MOPIDY}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 6680
      zeroconf:
        enabled: true
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_MOPIDY}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 6600
    persistence:
      media:
        enabled: true
        existingClaim: nas-music
      data:
        enabled: true
        existingClaim: mopidy-data
    config:
      snapserver:
        ip: ${SVC_IP_SNAPSERVER}
        port: 4955
      scrobbler:
        username: ${SECRET_LASTFM_USERNAME}
        password: ${SECRET_LASTFM_PASSWORD}
      enableTidal: true
