---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopidy-data
  namespace: radio
  labels:
    snapshot.home.arpa/enabled: "false"
    app.kubernetes.io/name: mopidy
    app.kubernetes.io/instance: mopidy
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
