---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gaps
  namespace: media
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-system
  - name: cert-manager
    namespace: kube-system
  - name: oauth2-proxy
    namespace: kube-system
  - name: vpn-gateway
    namespace: vpn
  - name: longhorn
    namespace: longhorn-system
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: gaps
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Berlin
    podAnnotations:
      setVPNGateway: "true"
    persistence:
      config:
        enabled: true
        existingClaim: gaps-config
    podSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: zerossl
          nginx.ingress.kubernetes.io/auth-url: "https://auth.buvis.net/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.buvis.net/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
        hosts:
        - host: gaps.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - gaps.buvis.net
          secretName: gaps-crt
    probes:
      startup:
        spec:
          initialDelaySeconds: 90
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 300
