---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supabase-db
  namespace: development
spec:
  dependsOn:
  - name: flux-system-extras
    namespace: flux-system
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: tdeoliv/supabase-bitnami-postgres
      tag: latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SECRET_SUPABASE_DB_PASSWORD}
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    service:
      main:
        ports:
          http:
            port: 5432
    persistence:
      data:
        enabled: true
        existingClaim: supabase-db
        mountPath: /var/lib/postgresql/data
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
