---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-tools
resources:
- ./dashboard
- ./helmrelease.yaml
labels:
- pairs:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
