---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkace-db
  namespace: gtd
  labels:
    app.kubernetes.io/name: linkace-db
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
