---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: smarthome
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  dependsOn:
  - name: ingress-nginx
    namespace: kube-system
  - name: cert-manager
    namespace: kube-system
  - name: longhorn
    namespace: longhorn-system
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.1.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Berlin
    persistence:
      config:
        enabled: true
        existingClaim: hass-config
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
