---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: smarthome
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-system
  - name: cert-manager
    namespace: kube-system
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Berlin
    persistence:
      config:
        enabled: true
        existingClaim: hass-config
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: zerossl
        hosts:
        - host: hass.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: hass-crt
          hosts:
          - hass.buvis.net
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.2.0
        workingDir: "/config"
        args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.buvis.net/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.buvis.net/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
          hosts:
          - host: hass-editor.buvis.net
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - hass-editor.buvis.net
        volumeMounts:
        - name: config
          mountPath: /config
