# Reference: https://medium.com/@markmcwhirter/alternative-acme-via-cert-manager-a9e9e7f105e0
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: zVMjbqGmgw9tV8SbB4thWg
      keySecretRef:
        name: zerossl-eab
        key: hmac
    privateKeySecretRef:
      name: zerossl-pkey
    solvers:
    - http01:
        ingress:
          class: nginx
