---
# main task file for roles/install-k3s-worker

- name: wait for ssh
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- name: install or upgrade k3s as worker
  shell: "curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_URL={{ k3s_master_api }} K3S_TOKEN={{ vault_k3s_token }} sh -"
  args:
    warn: false
