---
# handler for role upgrade-host
#

- name: check if running k3s
  stat:
    path: /usr/local/bin/k3s-killall.sh
  register: has_k3s

- name: stop k3s
  script:
    executable: /usr/local/bin/k3s-killall.sh
  when: has_k3s

- name: reboot
  reboot:
  notify: "wait for boot"

- name: wait for boot
  wait_for:
    port: 22
    host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
    delay: 5
    sleep: 5
    timeout: 120
