---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus-rules
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster-home/operations/monitoring/prometheus/rules
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
