---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "false"
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/instance: sabnzbd
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
