---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkace-db
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: openebs-jiva-csi-default
  csi:
    driver: jiva.csi.openebs.io
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkace-db
  namespace: gtd
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  volumeName: linkace-db
