---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: media
spec:
  dependsOn:
  - name: vpn-gateway
    namespace: vpn
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      annotations:
        setVPNGateway: "true"
    controllers:
      main:
        controllerType: deployment
        containers:
          main:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.3.14
            env:
              PUID: 1001
              PGID: 1001
            resources:
              requests:
                cpu: 15m
                memory: 105Mi
              limits:
                memory: 292Mi
    service:
      main:
        ports:
          http:
            port: 8191
