---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://angelnu.github.io/helm-charts
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.10.0
    DNS: 172.16.1.1
    routed_namespaces:
    - media
    publicPorts:
    - hostname: torr
      IP: 2
      ports:
      - type: tcp
        port: ${SECRET_VPN_BT_FORWARD_PORT}
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: ${NETWORK_CIDR_K8S_CLUSTER} ${NETWORK_CIDR_K8S_SERVICE} ${NETWORK_CIDR_K8S_SERVICE_EXTERNAL} ${NETWORK_CIDR_HOST}
      VPN_INTERFACE: tun0
      VPN_TRAFFIC_PORT: ${SECRET_VPN_GATEWAY_PORT}
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_LOCAL_CIDRS: ${NETWORK_CIDR_K8S_CLUSTER} ${NETWORK_CIDR_K8S_SERVICE} ${NETWORK_CIDR_K8S_SERVICE_EXTERNAL} ${NETWORK_CIDR_HOST}
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0
      gatewayDefault: false
      gatewayLabel: setVPNGateway
      gatewayAnnotation: setVPNGateway
    addons:
      netshoot:
        enabled: true
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: latest@sha256:729e54e9ac781f634157d43b564e02b0f3d8cb60aa70234f20db70f3c8abd566
        env:
        - name: VPN_SERVICE_PROVIDER
          value: ${SECRET_VPN_GATEWAY_PROVIDER}
        - name: VPN_TYPE
          value: openvpn
        - name: VPN_INTERFACE
          value: tun0
        - name: OPENVPN_USER
          value: ${SECRET_VPN_GATEWAY_USER}
        - name: OPENVPN_PASSWORD
          value: ${SECRET_VPN_GATEWAY_PASSWORD}
        #- name: SERVER_COUNTRIES
          #value: ${SECRET_VPN_GATEWAY_COUNTRIES}
        - name: LOG_LEVEL
          value: debug
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: ${NETWORK_CIDR_K8S_CLUSTER},${NETWORK_CIDR_K8S_SERVICE},${NETWORK_CIDR_K8S_SERVICE_EXTERNAL},${NETWORK_CIDR_HOST}
        - name: DOT
          value: off
        - name: HEALTH_TARGET_ADDRESS
          value: 1.1.1.1
        - name: HEALTH_VPN_DURATION_INITIAL
          value: 30s
        - name: TZ
          value: ${TIMEZONE}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        networkPolicy:
          enabled: true
          egress:
          - to:
            - ipBlock:
                cidr: 0.0.0.0/0
            ports:
            - port: ${SECRET_VPN_GATEWAY_PORT}
              protocol: UDP
          - to:
            - ipBlock:
                cidr: ${NETWORK_CIDR_K8S_CLUSTER}
          - to:
            - ipBlock:
                cidr: ${NETWORK_CIDR_K8S_SERVICE}
          - to:
            - ipBlock:
                cidr: ${NETWORK_CIDR_K8S_SERVICE_EXTERNAL}
          - to:
            - ipBlock:
                cidr: ${NETWORK_CIDR_HOST}
