---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://angelnu.github.io/helm-charts
      chart: pod-gateway
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1
    DNS: 172.16.1.1
    routed_namespaces:
    - media
    publicPorts:
    - hostname: torr
      IP: 2
      ports:
      - type: tcp
        port: ${SECRET_VPN_BT_FORWARD_PORT}
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: ${NETWORK_CIDR_K8S_CLUSTER} ${NETWORK_CIDR_K8S_SERVICE} ${NETWORK_CIDR_K8S_SERVICE_EXTERNAL} ${NETWORK_CIDR_HOST}
      VPN_INTERFACE: wg0
      VPN_TRAFFIC_PORT: ${SECRET_VPN_GATEWAY_ENDPOINT_PORT}
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_LOCAL_CIDRS: ${NETWORK_CIDR_K8S_CLUSTER} ${NETWORK_CIDR_K8S_SERVICE} ${NETWORK_CIDR_K8S_SERVICE_EXTERNAL} ${NETWORK_CIDR_HOST}
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.7.0
      gatewayDefault: false
      gatewayLabel: setVPNGateway
      gatewayAnnotation: setVPNGateway
    additionalContainers:
      gluetun:
        image: qmcgaw/gluetun:v3.32.0@sha256:70e2b9fe66941d6de31419c3207b525293f2e6a92a3788869bb337a17e0e5ec8
        env:
        - name: VPN_SERVICE_PROVIDER
          value: custom
        - name: VPN_TYPE
          value: wireguard
        - name: VPN_INTERFACE
          value: wg0
        - name: VPN_ENDPOINT_IP
          value: ${SECRET_VPN_GATEWAY_ENDPOINT_IP}
        - name: VPN_ENDPOINT_PORT
          value: ${SECRET_VPN_GATEWAY_ENDPOINT_PORT}
        - name: WIREGUARD_PUBLIC_KEY
          value: ${SECRET_VPN_GATEWAY_WG_PUBLIC_KEY}
        - name: WIREGUARD_PRIVATE_KEY
          value: ${SECRET_VPN_GATEWAY_WG_PRIVATE_KEY}
        - name: WIREGUARD_ADDRESSES
          value: ${SECRET_VPN_GATEWAY_WG_ADDRESSES}
        - name: FIREWALL
          value: "off"
        - name: DOT
          value: "off"
        - name: HEALTH_TARGET_ADDRESS
          value: "1.1.1.1"
        - name: HEALTH_VPN_DURATION_INITIAL
          value: 30s
        - name: TZ
          value: ${TIMEZONE}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
