---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://angelnu.github.io/helm-charts
      chart: pod-gateway
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.7.0
      gatewayDefault: false
      gatewayLabel: setVPNGateway
      gatewayAnnotation: setVPNGateway
    addons:
      vpn:
        enabled: true
        type: openvpn
        openvpn:
          image:
            repository: dperson/openvpn-client
            pullPolicy: Always
            tag: latest
          auth: ${SECRET_VPN_GATEWAY_AUTH}
        env:
          TZ: ${TIMEZONE}
        configFileSecret: vpn-gateway-openvpn-config
        resources:
          requests:
            cpu: "0.001"
            memory: 128Mi
          limits:
            memory: 512Mi
        securityContext:
          privileged: true
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - if [ $(wget -q -O- https://ipinfo.io/country) == '${SECRET_VPN_GATEWAY_COUNTRY}' ]; then exit 0; else exit $?; fi
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3
        networkPolicy:
          enabled: true
          egress:
          - to:
            - ipBlock:
                cidr: 0.0.0.0/0
            ports:
            - port: ${SECRET_VPN_GATEWAY_PORT}
              protocol: UDP
          - to:
            - ipBlock:
                cidr: ${NETWORK_CIDR_K8S_CLUSTER}
            - ipBlock:
                cidr: ${NETWORK_CIDR_K8S_SERVICE}
            - ipBlock:
                cidr: ${NETWORK_CIDR_K8S_SERVICE_EXTERNAL}
    routed_namespaces:
    - media
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: ${NETWORK_CIDR_K8S_CLUSTER} ${NETWORK_CIDR_K8S_SERVICE} ${NETWORK_CIDR_K8S_SERVICE_EXTERNAL} ${NETWORK_CIDR_HOST}
      VPN_INTERFACE: tun0
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_TRAFFIC_PORT: ${SECRET_VPN_GATEWAY_PORT}
      VPN_LOCAL_CIDRS: ${NETWORK_CIDR_K8S_CLUSTER} ${NETWORK_CIDR_K8S_SERVICE} ${NETWORK_CIDR_K8S_SERVICE_EXTERNAL} ${NETWORK_CIDR_HOST}
    publicPorts:
    - hostname: torr
      IP: 2
      ports:
      - type: tcp
        port: ${SECRET_VPN_BT_FORWARD_PORT}
