---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: oauth2-proxy
    namespace: kube-tools
  - name: vpn-gateway
    namespace: vpn
  - name: openebs
    namespace: storage
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/onedr0p/lidarr
      tag: 1.0.2.2592@sha256:5b012597e69e4540bf700b7519b663e9180e8a2b3e30b3f7b59e03f48ceae9eb
    env:
      TZ: ${TIMEZONE}
    podAnnotations:
      setVPNGateway: "true"
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config
      media:
        enabled: true
        existingClaim: nas-media
        mountPath: /media
    service:
      main:
        ports:
          http:
            port: 8686
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-url: "https://auth.buvis.net/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.buvis.net/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
        hosts:
        - host: lidarr.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - lidarr.buvis.net
          secretName: lidarr-crt
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 985
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
