---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: authentik
    namespace: security
  - name: vpn-gateway
    namespace: vpn
  - name: openebs
    namespace: storage
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/onedr0p/lidarr
      tag: 1.1.4.3027@sha256:74ff600e40d165684005da1fdf9d050d9d7e087caf74733c34e255a55784b6fe
    env:
      LIDARR_API_KEY: ${SECRET_LIDARR_API_KEY}
    podAnnotations:
      setVPNGateway: "true"
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config
      media:
        enabled: true
        existingClaim: nas-media
        mountPath: /media
    service:
      main:
        ports:
          http:
            port: 8686
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          authentik.home.arpa/enabled: "true"
        hosts:
        - host: lidarr.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - lidarr.buvis.net
          secretName: lidarr-crt
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 985
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
