---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkace
  namespace: flux-system
spec:
  dependsOn:
  - name: linkace-db
  interval: 5m
  path: "./gtd/linkace"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
