---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-vpn-sidecar
  annotations:
    policies.kyverno.io/title: Add VPN client sidecar
spec:
  rules:
    - name: add-vpn-sidecar
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
      mutate:
        patchStrategicMerge:
          spec:
            template:
              metadata:
                annotations:
                  (vpn/gluetun-inject): "true"
              spec:
                containers:
                  - name: gluetun
                    image: ghcr.io/qdm12/gluetun@sha256:97082faa51ec5f4dcb3921a5b70e74570761d05fd6841c4b853ffecb7b701943
                    env:
                      - name: FIREWALL_INPUT_PORTS
                        value: "6767,8191,8096,5055,8686,7373,9696,6881,7878,7373,8989,8265,8266,8080"
                      - name: FIREWALL_OUTBOUND_SUBNETS
                        value: "${NETWORK_CIDR_K8S_CLUSTER},${NETWORK_CIDR_K8S_SERVICE},${NETWORK_CIDR_K8S_SERVICE_EXTERNAL},${NETWORK_CIDR_HOST}"
                      - name: VPN_SERVICE_PROVIDER
                        value: ${SECRET_VPN_GATEWAY_PROVIDER}
                      - name: OPENVPN_USER
                        value: ${SECRET_VPN_GATEWAY_USER}
                      - name: OPENVPN_PASSWORD
                        value: ${SECRET_VPN_GATEWAY_PASSWORD}
                      - name: VPN_PORT_FORWARDING_LISTENING_PORT
                        value: "'${SECRET_VPN_BT_FORWARD_PORT}'"
                      - name: TZ
                        value: ${TIMEZONE}
                    securityContext:
                      runAsUser: 0
                      capabilities:
                        add:
                          - NET_ADMIN
