---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-vpn-sidecar
  annotations:
    policies.kyverno.io/title: Add VPN client sidecar
spec:
  rules:
    - name: add-vpn-sidecar
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
      mutate:
        patchStrategicMerge:
          spec:
            template:
              metadata:
                annotations:
                  (vpn/gluetun-inject): "true"
              spec:
                containers:
                  - name: gluetun
                    image: ghcr.io/qdm12/gluetun@sha256:ce3cd24a4dc26426a313bb117d2f13e33ea0233e7673a532932fdee8de05c835
                    env:
                      - name: FIREWALL_OUTBOUND_SUBNETS
                        value: "${NETWORK_CIDR_K8S_CLUSTER},${NETWORK_CIDR_K8S_SERVICE},${NETWORK_CIDR_K8S_SERVICE_EXTERNAL},${NETWORK_CIDR_HOST}"
                      - name: VPN_SERVICE_PROVIDER
                        value: ${SECRET_VPN_GATEWAY_PROVIDER}
                      - name: OPENVPN_USER
                        value: ${SECRET_VPN_GATEWAY_USER}
                      - name: OPENVPN_PASSWORD
                        value: ${SECRET_VPN_GATEWAY_PASSWORD}
                      - name: VPN_PORT_FORWARDING_LISTENING_PORT
                        value: "'${SECRET_VPN_BT_FORWARD_PORT}'"
                      - name: TZ
                        value: ${TIMEZONE}
                    securityContext:
                      runAsUser: 0
                      capabilities:
                        add:
                          - NET_ADMIN
