---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "false"
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/instance: bazarr
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
