- op: add
  path: /cluster/network/cni
  value:
    name: none
- op: add
  path: /cluster/proxy
  value:
    disabled: true
- op: replace
  path: /cluster/network/podSubnets
  value:
    - 172.22.0.0/16
- op: replace
  path: /cluster/network/serviceSubnets
  value:
    - 172.24.0.0/16
- op: add
  path: /machine/disks
  value:
    - device: /dev/sdb
      partitions:
        - mountpoint: /var/openebs/local
- op: replace
  path: /machine/install/wipe
  value: true
- op: add
  path: /machine/install/extensions
  value:
    - image: "ghcr.io/siderolabs/iscsi-tools:v0.1.5@sha256:571f4e94f38f32ca716c3f9f701c59f47c226eca4e2f9adfbb8b931b01fa1442"
    # - image: "ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:3ab305068aa28513b26ab3c5b1f2937dbe3f63b9c50abe290287cc58eb454bb9" # https://github.com/siderolabs/extensions/issues/237
- op: add
  path: /machine/install/diskSelector
  value:
    size: <100GB
- op: add
  path: /machine/kubelet
  value:
    extraMounts:
      - destination: /var/openebs/local
        type: bind
        source: /var/openebs/local
        options:
          - bind
          - rshared
          - rw
- op: add
  path: /machine/time
  value:
    disabled: false
    servers:
      - "time.cloudflare.com"
      - "time.google.com"
      - "pool.ntp.org"
    bootTimeout: 2m0s
