- op: add
  path: /cluster/network/cni
  value:
    name: custom
    urls:
    - https://docs.projectcalico.org/manifests/tigera-operator.yaml
    - https://raw.githubusercontent.com/buvis/clusters/main/cluster-home/infrastructure/manifests/install-calico.yaml
- op: replace
  path: /cluster/network/podSubnets
  value:
  - 172.22.0.0/16
- op: replace
  path: /cluster/network/serviceSubnets
  value:
  - 172.24.0.0/16
- op: add
  path: /machine/disks
  value:
  - device: /dev/sdb
    partitions:
    - mountpoint: /var/openebs/local
- op: replace
  path: /machine/install/wipe
  value: true
- op: add
  path: /machine/install/extensions
  value:
  - image: "ghcr.io/siderolabs/iscsi-tools:v0.1.1"
- op: add
  path: /machine/install/diskSelector
  value:
    busPath: /pci0000:00/0000:00:05.0/virtio1/host0/target0:0:0/0:0:0:0/
- op: add
  path: /machine/kubelet
  value:
    extraMounts:
    - destination: /var/openebs/local
      type: bind
      source: /var/openebs/local
      options:
      - bind
      - rshared
      - rw
- op: add
  path: /machine/time
  value:
    disabled: false
    servers:
    - 'time.cloudflare.com'
    - 'time.google.com'
    - 'pool.ntp.org'
    bootTimeout: 2m0s
