---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
  namespace: smarthome
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: hass
    app.kubernetes.io/instance: hass
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
