---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: jiva
      # renovate: registryUrl=https://openebs.github.io/jiva-operator
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    localprovisioner:
      enabled: true
      basePath: "/var/openebs/local"
  postRenderers:
    patches:
    - patch: |
        - op: add
          path: "/spec/template/spec/hostPID"
          value: true
      target:
        kind: daemonset
        name: openebs-jiva-csi-node
        namespace: storage
