---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: storage
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 5m
  chart:
    spec:
      chart: jiva
      # renovate: registryUrl=https://openebs.github.io/jiva-operator
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    localprovisioner:
      enabled: true
      basePath: "/var/openebs/local"
  postRenderers:
  - kustomize:
      patches:
      - patch: |
          - op: add
            path: "/spec/template/spec/hostPID"
            value: true
        target:
          kind: daemonset
          name: openebs-jiva-csi-node
          namespace: storage
      - patch: |
          - op: replace
            path: "/data/iscsiadm"
            value: |
              #!/bin/sh
              iscsid_pid=$(pgrep iscsid)
              nsenter --mount="/proc/${iscsid_pid}/ns/mnt" --net="/proc/${iscsid_pid}/ns/net" -- /usr/local/sbin/iscsiadm "$@"
        target:
          kind: configmap
          name: openebs-jiva-csi-iscsiadm
          namespace: storage
