---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.14.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured
        namespace: flux-system
      interval: 5m
  values:
    updateStrategy: RollingUpdate
    configuration:
      timeZone: Europe/Berlin
      period: 10m
      startTime: 0:00
      endTime: 7:00
      drainGracePeriod: 1800
      drainTimeout: 2000s
      slackHookUrl: ${SECRET_SLACK_KURED_WEBHOOK}
      slackChannel: kured
    tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
    - effect: NoSchedule
      operator: Exists
