---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: baikal
  namespace: gtd
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ckulka/baikal
              tag: 0.9.4-nginx
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
        - host: cal.buvis.net
          paths:
          - path: /
            pathType: Prefix
            service:
              name: main
              port: http
        tls:
        - hosts:
          - cal.buvis.net
          secretName: cal-crt
    persistence:
      config:
        enabled: true
        existingClaim: nas-pv-gtd
        globalMounts:
        - path: /var/www/baikal/config
          subPath: gtd/baikal/config
      data:
        enabled: true
        existingClaim: nas-pv-gtd
        globalMounts:
        - path: /var/www/baikal/Specific
          subPath: gtd/baikal/data
