---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: baikal
  namespace: gtd
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ckulka/baikal
      tag: 0.9.3-nginx
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
        - host: cal.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - cal.buvis.net
          secretName: cal-crt
    persistence:
      config:
        enabled: true
        mountPath: /var/www/baikal/config
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER_IP}"
            path: "${NFS_SERVER_PATH_BAIKAL}/config"
      data:
        enabled: true
        mountPath: /var/www/baikal/Specific
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER_IP}"
            path: "${NFS_SERVER_PATH_BAIKAL}/data"
