---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-music
spec:
  storageClassName: nas-music
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_SERVER_PATH_MEDIA}/music
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
  - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-music
  namespace: radio
spec:
  storageClassName: nas-music
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
