---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    routed_namespaces:
    - media
    publicPorts:
    - hostname: qbittorrent
      IP: 10
      ports:
      - type: udp
        port: ${SECRET_QB_VPN_FORWARD_PORT}
      - type: tcp
        port: ${SECRET_QB_VPN_FORWARD_PORT}
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: ${NETWORK_K8S_CLUSTER_CIDR} ${NETWORK_K8S_SERVICE_CIDR} ${NETWORK_K8S_SERVICE_EXTERNAL_CIDR} ${NETWORK_MANAGEMENT_CIDR}
      VPN_INTERFACE: tun0
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_TRAFFIC_PORT: ${SECRET_VPN_GATEWAY_PORT}
      VPN_LOCAL_CIDRS: ${NETWORK_K8S_CLUSTER_CIDR} ${NETWORK_K8S_SERVICE_CIDR} ${NETWORK_K8S_SERVICE_EXTERNAL_CIDR} ${NETWORK_MANAGEMENT_CIDR}
    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.4.0
      gatewayDefault: false
      gatewayLabel: setVPNGateway
      gatewayAnnotation: setVPNGateway
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - if [ $(wget -q -O- https://ipinfo.io/country) == '${SECRET_VPN_GATEWAY_COUNTRY}' ]; then exit 0; else exit $?; fi
      initialDelaySeconds: 30
      periodSeconds: 60
      failureThreshold: 1
    addons:
      vpn:
        enabled: true
        type: openvpn
        openvpn:
          image:
            repository: dperson/openvpn-client
            pullPolicy: Always
            tag: latest
          auth: ${SECRET_VPN_GATEWAY_AUTH}
        env:
          TZ: Europe/Berlin
        configFileSecret: vpn-gateway-openvpn-config
        resources:
          requests:
            cpu: "0.001"
            memory: 128Mi
          limits:
            memory: 512Mi
        networkPolicy:
          enabled: true
          egress:
          - to:
            - ipBlock:
                cidr: 0.0.0.0/0
            ports:
            - port: ${SECRET_VPN_GATEWAY_PORT}
              protocol: UDP
          - to:
            - ipBlock:
                cidr: ${NETWORK_K8S_CLUSTER_CIDR}
            - ipBlock:
                cidr: ${NETWORK_K8S_SERVICE_CIDR}
            - ipBlock:
                cidr: ${NETWORK_K8S_SERVICE_EXTERNAL_CIDR}
