---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: network
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.truecharts.org
      chart: blocky
      version: 4.0.3
      sourceRef:
        kind: HelmRepository
        name: TrueCharts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicas: 3
    service:
      dnstcp:
        enabled: true
        ports:
          dnstcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_BLOCKY}
        externalTrafficPolicy: Local
      dnsudp:
        enabled: true
        ports:
          dnsudp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_BLOCKY}
        externalTrafficPolicy: Local
    probes:
      liveness:
        failureThreshold: 5
        periodSeconds: 10
      readiness:
        failureThreshold: 5
        periodSeconds: 10
      startup:
        initialDelaySeconds: 5
        failureThreshold: 30
        periodSeconds: 10
    metrics:
      enabled: false
    blockyConfig: |
      upstream:
        externalResolvers:
          - udp:${GATEWAY_IP}
      blocking:
        blackLists:
          ads:
          - https://raw.githubusercontent.com/buvis/clusters/main/cluster-home/operations/network/blocky/blacklist.txt
          - https://dbl.oisd.nl/
          #- http://sysctl.org/cameleon/hosts
          #- https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          #- https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          #- https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          #- https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist1.txt
          #- https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist2.txt
          #- https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist3.txt
          #- https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist4.txt
          #- https://raw.githubusercontent.com/kodlz/pihole_easylist/main/adblock_list/adblock.hosts
          #- https://raw.githubusercontent.com/herrbischoff/trackers/master/trackers.txt
          #- https://raw.githubusercontent.com/herrbischoff/trackers/master/domains.txt
          #- https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/smartphone-ads-tracking.txt
          #- https://codeberg.org/spootle/blocklist/raw/branch/master/blocklist.txt
          #- https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.txt
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
          - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/filter_whitelist.txt
          - https://raw.githubusercontent.com/buvis/clusters/main/cluster-home/operations/network/blocky/whitelist.txt
        clientGroupsBlock:
          default:
          - ads
      conditional:
        mapping:
          buvis.net: udp:${GATEWAY_IP}
      clientLookup:
        upstream: udp:${GATEWAY_IP}
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
