---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: network
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.21
    controller:
      replicas: 3
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        enabled: true
        ports:
          http:
            port: 4000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_BLOCKY}
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
      dns-udp:
        enabled: true
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_BLOCKY}
        externalTrafficPolicy: Local
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    probes:
      liveness:
        failureThreshold: 5
        periodSeconds: 10
      readiness:
        failureThreshold: 5
        periodSeconds: 10
      startup:
        initialDelaySeconds: 5
        failureThreshold: 30
        periodSeconds: 10
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - blocky
            topologyKey: kubernetes.io/hostname
    persistence:
      config:
        enabled: true
        type: configMap
        name: &config blocky-config
        subPath: config.yml
        mountPath: /app/config.yml
        readOnly: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: *config
    configMaps:
      config:
        enabled: true
        data:
          config.yml: |
            upstream:
              default:
              - ${GATEWAY_IP}
            blocking:
              blackLists:
                ads:
                - https://raw.githubusercontent.com/buvis/clusters/main/cluster-home/operations/network/blocky/blacklist.txt
                - https://dbl.oisd.nl/
                #- http://sysctl.org/cameleon/hosts
                #- https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
                #- https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
                #- https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
                #- https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist1.txt
                #- https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist2.txt
                #- https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist3.txt
                #- https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist4.txt
                #- https://raw.githubusercontent.com/kodlz/pihole_easylist/main/adblock_list/adblock.hosts
                #- https://raw.githubusercontent.com/herrbischoff/trackers/master/trackers.txt
                #- https://raw.githubusercontent.com/herrbischoff/trackers/master/domains.txt
                #- https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/smartphone-ads-tracking.txt
                #- https://codeberg.org/spootle/blocklist/raw/branch/master/blocklist.txt
                #- https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.txt
              whiteLists:
                ads:
                - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
                - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/filter_whitelist.txt
                - https://raw.githubusercontent.com/buvis/clusters/main/cluster-home/operations/network/blocky/whitelist.txt
              clientGroupsBlock:
                default:
                - ads
            conditional:
              mapping:
                buvis.net: ${GATEWAY_IP}
            clientLookup:
              upstream: ${GATEWAY_IP}
            prometheus:
              enable: true
              path: /metrics
            httpPort: 4000
            logLevel: info
