---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster-home/operations/monitorin/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: Secret
      name: cluster-secret-vars
    - kind: ConfigMap
      name: cluster-config
