---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
resources:
- helmrelease.yaml
- kube-prometheus-stack.yaml
- servicemonitors.yaml
