---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack-rules
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./production/operations/monitoring/kube-prometheus-stack/rules
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
