---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-exec
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduled-task
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scheduled-task-pods-list-exec
  namespace: media
subjects:
  - kind: ServiceAccount
    name: scheduled-task
    namespace: default
roleRef:
  kind: ClusterRole
  name: pods-list-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: beets-update
  namespace: media
spec:
  schedule: "13 0 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: beets-update
              image: buvis/kube-exec:latest
              env:
                - name: NAMESPACE
                  value: media
                - name: LABEL
                  value: "app.kubernetes.io/name=beets-update"
                - name: COMMAND
                  value: 'find /media/music -type d -name "_LIDARR_ADDITIONS" | sort | xargs -I {} beet import -q "{}" && beet update && beet move'
          serviceAccountName: scheduled-task
          restartPolicy: OnFailure
