---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.1.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      hostNetwork: true
      service:
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_INGRESS}
        externalTrafficPolicy: Local
      config:
        client-header-buffer-size: "128k"
        large-client-header-buffers: "4 128k"
        proxy-body-size: "4096m"
        proxy-buffer-size: "128k"
        proxy-connect-timeout: "600s"
        proxy-read-timeout: "3600s"
        proxy-request-buffering: "off"
        proxy-send-timeout: "3600s"
        server-tokens: "false"
        worker-shutdown-timeout: "3600s"
      replicaCount: 5
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - ingress-nginx
              topologyKey: kubernetes.io/hostname
