---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media-downloads
spec:
  storageClassName: nas-media-downloads
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${FAST_NAS_SERVER_IP}
    path: ${FAST_NAS_PATH_MEDIA}/downloads
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media-downloads
  namespace: media
spec:
  storageClassName: nas-media-downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media-music
spec:
  storageClassName: nas-media-music
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${FAST_NAS_SERVER_IP}
    path: ${FAST_NAS_PATH_MEDIA}/music
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media-music
  namespace: media
spec:
  storageClassName: nas-media-music
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media-music-inbox
spec:
  storageClassName: nas-media-music-inbox
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${FAST_NAS_SERVER_IP}
    path: ${FAST_NAS_PATH_MEDIA}/music-inbox
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media-music-inbox
  namespace: media
spec:
  storageClassName: nas-media-music-inbox
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media-videos
spec:
  storageClassName: nas-media-videos
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_SERVER_PATH_MEDIA}/videos
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media-videos
  namespace: media
spec:
  storageClassName: nas-media-videos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-pv-media
spec:
  storageClassName: nas-pv-media
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${FAST_NAS_SERVER_IP}
    path: ${FAST_NAS_PATH_PV}/media
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-pv-media
  namespace: media
spec:
  storageClassName: nas-pv-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
