---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica
  namespace: gtd
spec:
  dependsOn:
  - name: monica-db
    namespace: gtd
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: monica
      version: 7.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/stable/monica/values.yaml
  values:
    image:
      repository: monica
      tag: 3.7.0-apache
      pullPolicy: IfNotPresent
    env:
      APP_ENV: production
      APP_KEY: ${SECRET_MONICA_APP_KEY}
      APP_URL: https://crm.buvis.net
      DB_DATABASE: monica
      DB_HOST: monica-db-mariadb
      DB_PASSWORD: ${SECRET_MONICA_DB_PASSWORD}
      DB_USERNAME: monica
      DEFAULT_MAX_UPLOAD_SIZE: 50000
      TZ: Europe/Berlin
    persistence:
      config:
        enabled: true
        existingClaim: monica-config
    mariadb:
      enabled: false
    ingress:
      main:
        enabled: false
    probes:
      startup:
        spec:
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 300
