---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mopidy
  namespace: radio
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.buvis.net
      chart: mopidy
      version: 0.5.6
      sourceRef:
        kind: HelmRepository
        name: buvis
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/buvis/mopidy
      tag: v3.69.3@sha256:a7ae8e2d12cbaba49de0be84e98740d9124d1371c86d8eab78401b1ee3c09bbc
    service:
      main:
        enabled: true
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_MOPIDY}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 6680
      zeroconf:
        enabled: true
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_MOPIDY}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 6600
    persistence:
      media:
        enabled: true
        existingClaim: nas-music
      data:
        enabled: true
        existingClaim: mopidy-data
    config:
      snapserver:
        ip: ${SVC_IP_SNAPSERVER}
        port: 4955
      scrobbler:
        username: ${SECRET_LASTFM_USERNAME}
        password: ${SECRET_LASTFM_PASSWORD}
      enableTidal: true
      defaultPlaylist: radio-1-fm-bom-psytrance
