---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mopidy-data
spec:
  storageClassName: mopidy-data
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_SERVER_PATH_MOPIDY}
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
  - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopidy-data
  namespace: radio
spec:
  storageClassName: mopidy-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
